### ISSUE TITLE
로스트아크 웹 경매장의 정렬 문제

### ISSUE THREAD

**Issue by icepeng** [icepeng/loa-calc#8]
![image](https://user-images.githubusercontent.com/12782606/147894737-74aa6237-d5de-4d78-bc82-a8cd73afacd3.png)

즉시 구매가 순으로 정렬시, 인게임과는 다르게 즉시 구매가가 없는 매물이 먼저 나오고 있다.

이로 인해 1페이지에 즉시 구매가가 존재하는 아이템이 하나도 존재하지 않아 조합에 실패하는 현상이 발생한다.

**Comment by tyjeon** [comment]
첫 페이지에 즉시구매가가 없으면 바로 최대 페이지를 반환받고 10%, 20% 구간 페이지를 요청해 구매가가 있는 매물을 구할 수 있습니다.
신속, {"각성":3,"잡옵":3} 같은 경우 300페이지 이상 매물이 잡히는데, 30페이지와 60페이지만 검색하면 100골드 내외로 최저가가 잡힙니다. 실제 최저가는 아니나 충분히 작은 값이라 제 경우는 그대로 사용했습니다.

**Comment by icepeng** [comment]
@tyjeon 정보 제공해주셔서 감사합니다. 1페이지에 즉구가가 존재하지 않는 매물이면 충분히 싸다는 가정을 해도 괜찮다는 생각이 드네요. 트포의 경우 이 방법을 적용할 시 검색 요청 횟수가 최대 두배 가까이 늘어날 수 있어 더 고려해보고 적용을 시도하겠습니다.
